// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	pb "github.com/andre-ols/chatservice/internal/infra/grpc/pb"
	mock "github.com/stretchr/testify/mock"
)

// ChatServiceServer is an autogenerated mock type for the ChatServiceServer type
type ChatServiceServer struct {
	mock.Mock
}

// ChatStream provides a mock function with given fields: _a0, _a1
func (_m *ChatServiceServer) ChatStream(_a0 *pb.ChatRequest, _a1 pb.ChatService_ChatStreamServer) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*pb.ChatRequest, pb.ChatService_ChatStreamServer) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mustEmbedUnimplementedChatServiceServer provides a mock function with given fields:
func (_m *ChatServiceServer) mustEmbedUnimplementedChatServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewChatServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewChatServiceServer creates a new instance of ChatServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewChatServiceServer(t mockConstructorTestingTNewChatServiceServer) *ChatServiceServer {
	mock := &ChatServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
